package com.dream.dreamtv.db.entity;

import android.os.Parcel;
import android.os.Parcelable;

import androidx.room.Entity;
import androidx.room.PrimaryKey;
import androidx.room.Room;


/*
  Created by manuel on 21,August,2018
 */

/**
 * Defines the schema of a table in {@link Room} for a single weather
 * forecast.
 */
@Entity(tableName = "user_table")
public class UserEntity implements Parcelable {

    /**
     * Makes sure the id is the primary key (ensures uniqueness), is auto generated by {@link Room}.
     */
    @PrimaryKey(autoGenerate = true)
    public int id;
    public String token;
    public String email;
    public String password;
    public String sub_language;
    public String audio_language;
    public String interface_mode;
    public String interface_language;

    public UserEntity(String token, String email, String password, String sub_language,
                      String audio_language, int id, String interface_mode,
                      String interface_language) {
        this.token = token;
        this.email = email;
        this.password = password;
        this.sub_language = sub_language;
        this.audio_language = audio_language;
        this.id = id;
        this.interface_mode = interface_mode;
        this.interface_language = interface_language;
    }

    protected UserEntity(Parcel in) {
        token = in.readString();
        email = in.readString();
        password = in.readString();
        sub_language = in.readString();
        audio_language = in.readString();
        id = in.readInt();
        interface_mode = in.readString();
        interface_language = in.readString();
    }

    public static final Creator<UserEntity> CREATOR = new Creator<UserEntity>() {
        @Override
        public UserEntity createFromParcel(Parcel in) {
            return new UserEntity(in);
        }

        @Override
        public UserEntity[] newArray(int size) {
            return new UserEntity[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(token);
        dest.writeString(email);
        dest.writeString(password);
        dest.writeString(sub_language);
        dest.writeString(audio_language);
        dest.writeInt(id);
        dest.writeString(interface_mode);
        dest.writeString(interface_language);
    }
}
